rutas:
  excel: RegistrosApi.xlsx
  credenciales: Configuracion.txt
  RemisionTyC: RemisionTyC.txt
  FacturaTyC: FacturaTyC.txt
  FacturaNotas: FacturaNotas.txt
  apiAlegra: https://api.alegra.com/api/v1/